# Generated by Django 3.0.4 on 2020-04-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('app_name', models.CharField(blank=True, max_length=100, null=True)),
                ('developer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('developer_site', models.TextField()),
                ('rating', models.CharField(blank=True, max_length=100, null=True)),
                ('icon_url', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('refreshed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active_on_playstore', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SystemVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_scraping_running', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Variable',
                'verbose_name_plural': 'System Variables',
            },
        ),
        migrations.CreateModel(
            name='PackageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.TextField()),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', related_query_name='attachment', to='core.Package')),
            ],
            options={
                'verbose_name': 'Package Attachment',
                'verbose_name_plural': 'Package Attachments',
                'ordering': ('-created_at',),
            },
        ),
    ]
