# Generated by Django 3.0.4 on 2020-04-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='developer_site',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='icon_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
