# Generated by Django 3.0.4 on 2020-04-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200411_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemvariable',
            name='error_while_scraping',
            field=models.TextField(blank=True, null=True),
        ),
    ]
