# Generated by Django 3.0.4 on 2020-04-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemvariable_error_while_scraping'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('-created_at',), 'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.RemoveField(
            model_name='packageattachment',
            name='updated_at',
        ),
    ]
